# Deployment Target
platform :ios, '9.0'


# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!


target 'APTips_Example' do
    pod 'APTips', :path => '../'
end


post_install do |installer|
    # Add podInstall.command and podUpdate.command shell scripts to Pods project
    pods_project = installer.pods_project
    pods_project.new_file "../Scripts/Cocoapods/podInstall.command"
    pods_project.new_file "../Scripts/Cocoapods/podUpdate.command"
end
